apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: glh2zfw8z-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:c8fa08ce7ff1b83fd3bb8de945cd9c1ce72da8b7@sha256:07a2f76eb0edf247040465309ac7278b5458e33d3be74a027c5406023ae32617
          name: container-image
